# Generated by Django 6.0.4 on 2026-04-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('report_period', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='reports.distributor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='POSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_level_1', models.CharField(blank=True, max_length=200)),
                ('product_level_2', models.CharField(blank=True, max_length=200)),
                ('product_level_3', models.CharField(blank=True, max_length=200)),
                ('item_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer_part_no', models.CharField(blank=True, max_length=100)),
                ('product_description', models.TextField(blank=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_ref', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('invoiced_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('sda_number', models.CharField(blank=True, max_length=100)),
                ('special_bid_number', models.CharField(blank=True, max_length=100)),
                ('customer_account', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('address_street', models.CharField(blank=True, max_length=300)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reports.distributor')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reports.posupload')),
            ],
            options={
                'ordering': ['-invoice_date', 'customer_name'],
            },
        ),
    ]
