# Generated by Django 6.0.4 on 2026-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_distributor_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('rate_to_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
