# Generated by Django 4.2.30 on 2026-06-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_monthlyrate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyrate',
            new_name='reports_mon_year_6b614a_idx',
            old_name='reports_mon_year_43b9a1_idx',
        ),
    ]
